forci_menu_builder_client_menu_list:
    path:        /list
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:listAction

forci_menu_builder_client_menu_list_row_refresh:
    path:        /{id}/refresh/row
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:refreshListRowAction

forci_menu_builder_client_menu_name_update:
    path:        /{id}/update/name
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:updateNameAction

forci_menu_builder_client_menu_create:
    path:        /create
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:createAction

forci_menu_builder_client_menu_nestable:
    path:        /{id}/nestable/sort
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:nestableAction

forci_menu_builder_client_menu_nestable_refresh:
    path:        /{id}/refresh/nestable
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:refreshNestableAction

forci_menu_builder_client_menu_nestable_update:
    path:        /{id}/nestable/update
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:updateNestableAction

forci_menu_builder_client_menu_sortable:
    path:        /{id}/sortable/{class}/sort
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:sortableAction
    defaults:
        class: 'vertical-simple'
    requirements:
        class: 'vertical-simple|vertical-custom|vertical'

forci_menu_builder_client_menu_sortable_refresh:
    path:        /{id}/refresh/sortable
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:refreshSortableAction

forci_menu_builder_client_menu_sortable_update:
    path:        /{id}/sortable/update
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:updateSortableAction

forci_menu_builder_client_menu_remove:
    path:        /{id}/remove
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:removeAction
    requirements:
        id: \d+

forci_menu_builder_client_menu_item:
    resource: menu/item.yml
    prefix: /{id}/items

forci_menu_builder_client_menu_item_remove:
    path:        /items/remove
    controller: Forci\Bundle\MenuBuilderClient\Controller\MenuController:removeItemAction