forci_menu_builder_client_menu_item_name_update:
    path:        /{itemId}/update/name
    controller: Forci\Bundle\MenuBuilderClient\Controller\Menu\ItemController:updateItemNameAction

forci_menu_builder_client_menu_item_choose_route:
    path:        /add/choose-route/{parentId}
    controller: Forci\Bundle\MenuBuilderClient\Controller\Menu\ItemController:chooseRouteAction
    defaults:
        parentId: null
    requirements:
        id: \d+
        parentId: \d+

forci_menu_builder_client_menu_item_add:
    path:        /add/{routeId}/{parentId}
    controller: Forci\Bundle\MenuBuilderClient\Controller\Menu\ItemController:addItemAction
    defaults:
        parentId: null
    requirements:
        id: \d+
        routeId: \d+
        parentId: \d+

forci_menu_builder_client_menu_item_edit:
    path:        /{itemId}/edit
    controller: Forci\Bundle\MenuBuilderClient\Controller\Menu\ItemController:editItemAction
    requirements:
        id: \d+
        itemId: \d+