forci_menu_builder_client_dashboard:
    path:        /
    controller: Forci\Bundle\MenuBuilderClient\Controller\DashboardController:dashboardAction

forci_menu_builder_client_menu:
    resource: routing/menu.yml
    prefix: /menus