forci_menu_builder_client_dashboard:
    path:        /
    defaults:    { _controller: ForciMenuBuilderClientBundle:Dashboard:dashboard }

forci_menu_builder_client_menu:
    resource: routing/menu.yml
    prefix: /menus